name: Unity Actions

on: 
  push:
    branches:
    - main

jobs:
  buildAll:
    name: Build for ${{ matrix.targetPlatform }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.2.2f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      # Checkout
      - name: Checkout Files 👀
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - name: Cache Build Files 📦
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build Game Executables 🔧
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      # Output
      - name: Upload Artifacts 📁
      - uses: actions/upload-artifact@v2
        with:
          name: Celeritas-${{ matrix.targetPlatform }}
          path: build
  release:
    runs-on: ubuntu-latest
    needs: [buildAll]
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Celeritas-OSX.zip,Celeritas-Windows64.zip"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
  buildWIN: