name: Unity Actions

on: 
  push:
    tags:
    - '*'

jobs:
  buildAll:
    name: Build for ${{ matrix.targetPlatform }} 🔧
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.2.2f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneWindows # Build a Windows standalone. 
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
          # - WebGL # WebGL.
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Celeritas-${{ matrix.targetPlatform }}
          path: build
  release:
    name: Release Artifacts 📁
    runs-on: ubuntu-latest
    needs: [buildAll]
    steps:
    - uses: actions/download-artifact@v2
    with:
      path: ./
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*"
        token: ${{ secrets.GITHUB_TOKEN }}