name: Unity Actions

on: [push, pull_request]

jobs:
  buildWIN:
    name: Build Windows ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.2.2f1
          targetPlatform: StandaloneWindows64
          versioning: Semantic

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Celeritas-Windows64
          path: build
  buildOSX:
    name: Build OSX ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2020.2.2f1
          targetPlatform: StandaloneOSX
          versioning: Semantic

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Celeritas-OSX
          path: build
